version: '3.9'

services:
  web:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    networks:
      - minha_network
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    container_name: nodeapp
    build:
      context: .
      dockerfile: dockerfile
    expose: # Expõe a porta apenas internamente
      - "3000"
    networks:
      - minha_network
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    tty: true
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=minhaSenha
      - POSTGRES_DB=nodedb
    ports:
      - "5432:5432"
    networks:
      - minha_network

volumes:
  postgres_data:

networks:
  minha_network:
    driver: bridge